Repository metoppv/improver, pull requests merged in 2019-12, with the labels that each got.

#1016 Port -to-realizations CLIs to use clize
  lib/improver/cli/__init__.py
  lib/improver/cli/percentile.py
  lib/improver/cli/percentiles_to_realizations.py
  lib/improver/cli/probabilities_to_realizations.py
  lib/improver/tests/percentile/test_cli_percentile.py
  tests/improver-percentile/00-null.bats
  tests/improver-percentile/01-help.bats
  tests/improver-percentile/02-basic.bats
  tests/improver-percentile/03-probability_conversion_single_realization.bats
  tests/improver-percentile/04-probability_conversion_multi_realization.bats
  tests/improver-percentile/05-number_of_percentiles.bats
  tests/improver-percentile/06-masked_cube.bats
  tests/improver-percentile/07-ecc_bounds_warning.bats
  tests/improver-percentiles-to-realizations/00-null.bats
  tests/improver-percentiles-to-realizations/01-help.bats
  tests/improver-percentiles-to-realizations/02-percentiles_reordering.bats
  tests/improver-percentiles-to-realizations/03-percentiles_rebadging.bats
  tests/improver-percentiles-to-realizations/04-percentiles_rebading_extra_option.bats
  tests/improver-percentiles-to-realizations/05-reordering_wrong_options.bats
  tests/improver-percentiles-to-realizations/06-rebading_wrong_option1.bats
  tests/improver-percentiles-to-realizations/07-rebading_wrong_option2.bats
  tests/improver-percentiles-to-realizations/08-ecc_bounds_warning.bats
  tests/improver-probabilities-to-realizations/00-null.bats
  tests/improver-probabilities-to-realizations/01-help.bats
  tests/improver-probabilities-to-realizations/02-basic.bats
  tests/improver-probabilities-to-realizations/03-12_realizations.bats
  tests/improver-probabilities-to-realizations/04-reordering_no_raw_ens.bats
  tests/improver-probabilities-to-realizations/05-raw_ens_no_realizations.bats
  tests/improver-probabilities-to-realizations/06-reordering_basic.bats
  tests/improver-probabilities-to-realizations/07_rebadging_wrong_options1.bats
  tests/improver-probabilities-to-realizations/08_rebadging_wrong_options2.bats
  tests/improver-probabilities-to-realizations/09-reordering_6_reals.bats
  tests/improver-probabilities-to-realizations/10-ecc_bounds_warning.bats
Labels: green_team, suite_breaking

#1004 Enable Travis build config validation
  .travis.yml
Labels: green_team

#959 IMPRO-1195: create convert_to_realizations CLI
  lib/improver/cli/convert_to_realizations.py
  tests/improver-convert-to-realizations/01-percentiles.bats
  tests/improver-convert-to-realizations/02-probabilities.bats
Labels: green_team

#1026 Conversion of acceptance tests to pytest
  .travis.yml
  bin/improver-tests
  etc/pylintrc
  lib/improver/cli/__init__.py
  lib/improver/tests/acceptance/__init__.py
  lib/improver/tests/acceptance/acceptance.py
  lib/improver/tests/acceptance/test_apply_emos_coefficients.py
  lib/improver/tests/acceptance/test_apply_lapse_rate.py
  lib/improver/tests/acceptance/test_between_thresholds.py
  lib/improver/tests/acceptance/test_blend_adjacent_points.py
  lib/improver/tests/acceptance/test_combine.py
  lib/improver/tests/acceptance/test_create_grid_with_halo.py
  lib/improver/tests/acceptance/test_estimate_emos_coefficients.py
  lib/improver/tests/acceptance/test_extend_radar_mask.py
  lib/improver/tests/acceptance/test_extract.py
  lib/improver/tests/acceptance/test_feels_like_temp.py
  lib/improver/tests/acceptance/test_generate_landmask_ancillary.py
  lib/improver/tests/acceptance/test_generate_topography_bands.py
  lib/improver/tests/acceptance/test_nbhood.py
  lib/improver/tests/acceptance/test_nbhood_iterate_with_mask.py
  lib/improver/tests/acceptance/test_nbhood_land_and_sea.py
  lib/improver/tests/acceptance/test_neighbour_finding.py
  lib/improver/tests/acceptance/test_nowcast_extrapolate.py
  lib/improver/tests/acceptance/test_nowcast_optical_flow.py
  lib/improver/tests/acceptance/test_orographic_enhancement.py
  lib/improver/tests/acceptance/test_percentile.py
  lib/improver/tests/acceptance/test_percentiles_to_probabilities.py
  lib/improver/tests/acceptance/test_percentiles_to_realizations.py
  lib/improver/tests/acceptance/test_probabilities_to_realizations.py
  lib/improver/tests/acceptance/test_recursive_filter.py
  lib/improver/tests/acceptance/test_resolve_wind_components.py
  lib/improver/tests/acceptance/test_snow_falling_level.py
  lib/improver/tests/acceptance/test_spot_extract.py
  lib/improver/tests/acceptance/test_standardise.py
  lib/improver/tests/acceptance/test_temp_lapse_rate.py
  lib/improver/tests/acceptance/test_temporal_interpolate.py
  lib/improver/tests/acceptance/test_threshold.py
  lib/improver/tests/acceptance/test_time_lagged_ensembles.py
  lib/improver/tests/acceptance/test_update_grid_metadata.py
  lib/improver/tests/acceptance/test_uv_index.py
  lib/improver/tests/acceptance/test_weighted_blending.py
  lib/improver/tests/acceptance/test_wet_bulb_temperature.py
  lib/improver/tests/acceptance/test_wind_direction.py
  lib/improver/tests/acceptance/test_wind_downscaling.py
  lib/improver/tests/acceptance/test_wind_gust_diagnostic.py
  lib/improver/tests/acceptance/test_wxcode.py
  lib/improver/tests/conftest.py
  pytest.ini
  tests/improver-nbhood/.00-null.bats.swp
Labels: green_team

#1033 Fix codacy coverage and report combined unit/acceptance coverage
  .travis.yml
  bin/improver-tests
Labels: green_team

#1034 Clize: Combine CLI
  lib/improver/cli/combine.py
  lib/improver/tests/acceptance/test_combine.py
Labels: clize

#1043 Changes to convert feels like temperature to clize.
  lib/improver/cli/feels_like_temp.py
  lib/improver/tests/acceptance/test_feels_like_temp.py
Labels: clize

#1037 Clizify weighted blending CLI
  lib/improver/cli/weighted_blending.py
  lib/improver/tests/acceptance/test_weighted_blending.py
Labels: clize

#1036 Clize applied to apply-lapse-rate CLI
  lib/improver/cli/apply_lapse_rate.py
  lib/improver/tests/acceptance/test_apply_lapse_rate.py
Labels: clize

#1041 Fix duplicate clize output and errors
  lib/improver/cli/__init__.py
Labels: green_team

#1046 Clizes create-grid-with-halo
  lib/improver/cli/create_grid_with_halo.py
  lib/improver/tests/acceptance/test_create_grid_with_halo.py
Labels: clize

#1040 Convert create-grid-with-halo CLI to clize
  lib/improver/cli/create_grid_with_halo.py
  lib/improver/tests/acceptance/test_create_grid_with_halo.py
Labels: clize

#1047 Clize time lagging (2)
  lib/improver/blending/weighted_blend.py
  lib/improver/cli/time_lagged_ensembles.py
  lib/improver/metadata/forecast_times.py
  lib/improver/tests/acceptance/test_time_lagged_ensembles.py
  lib/improver/tests/metadata/test_forecast_times.py
  lib/improver/tests/utilities/test_GenerateTimeLaggedEnsemble.py
  lib/improver/utilities/time_lagging.py
Labels: clize

#1052 Conversion of extract to use clize.
  lib/improver/cli/extract.py
  lib/improver/tests/acceptance/test_extract.py
Labels: clize

#1055 Clize wet-bulb-temperature
  lib/improver/cli/wet_bulb_temperature.py
  lib/improver/tests/acceptance/test_wet_bulb_temperature.py
Labels: clize

#1059 clize changes for uv-index
  lib/improver/cli/uv_index.py
  lib/improver/tests/acceptance/test_uv_index.py
Labels: clize

#1058 Clize phase-change-level
  lib/improver/cli/phase_change_level.py
  lib/improver/tests/acceptance/test_phase_change_level.py
Labels: clize

#1060 Clize wet-bulb-temperature-integral
  lib/improver/cli/wet_bulb_temperature_integral.py
  lib/improver/psychrometric_calculations/psychrometric_calculations.py
  lib/improver/tests/acceptance/test_wet_bulb_temperature_integral.py
Labels: clize

#1062 Clize wind direction
  lib/improver/cli/wind_direction.py
  lib/improver/tests/acceptance/test_wind_direction.py
Labels: clize

#1038 Convert apply-emos-coefficients to clize
  lib/improver/cli/apply_emos_coefficients.py
  lib/improver/tests/acceptance/test_apply_emos_coefficients.py
Labels: clize

#1039 Convert blend-adjacent-points CLI to use clize
  lib/improver/cli/blend_adjacent_points.py
  lib/improver/tests/acceptance/test_blend_adjacent_points.py
Labels: clize

#1064 Clize threshold
  lib/improver/cli/threshold.py
  lib/improver/tests/acceptance/test_threshold.py
  lib/improver/threshold.py
Labels: clize

#1030 Tests with Github Actions
  .github/workflows/tests.yml
  environment.yml
Labels: green_team

#1048 Migrates spot-extract to use Clize.
  lib/improver/cli/spot_extract.py
  lib/improver/tests/acceptance/test_spot_extract.py
Labels: clize

#1049 Clize standardise
  lib/improver/cli/standardise.py
  lib/improver/tests/acceptance/test_standardise.py
Labels: clize

#1063 Clize topographic band CLIs
  lib/improver/cli/generate_topography_bands_mask.py
  lib/improver/cli/generate_topography_bands_weights.py
  lib/improver/generate_ancillaries/generate_ancillary.py
  lib/improver/tests/acceptance/test_generate_topography_bands.py
Labels: clize

#1067 Describes behaviour if optional output file is not supplied.
  lib/improver/cli/__init__.py
Labels: clize

#1074 between-thresholds CLI to clize
  lib/improver/cli/between_thresholds.py
  lib/improver/tests/acceptance/test_between_thresholds.py
Labels: clize

#1071 generate-landmask-ancillary CLI using clize
  lib/improver/cli/generate_landmask_ancillary.py
  lib/improver/tests/acceptance/test_generate_landmask_ancillary.py
Labels: clize

#1069 Impro 1497 clize percentiles to probabilities
  lib/improver/cli/percentiles_to_probabilities.py
  lib/improver/tests/acceptance/test_percentiles_to_probabilities.py
Labels: clize

#1073 neighbour-finding CLI to clize
  lib/improver/cli/neighbour_finding.py
  lib/improver/tests/acceptance/test_neighbour_finding.py
Labels: clize

#1056 IMPRO-1534: convert extend radar mask to use clize
  lib/improver/cli/extend_radar_mask.py
  lib/improver/tests/acceptance/test_extend_radar_mask.py
Labels: clize

#1080 Enable neighbour-finding CLI test that was marked as failing
  lib/improver/tests/acceptance/test_neighbour_finding.py
Labels: clize

#1076 wxcode CLI to clize
  lib/improver/cli/wxcode.py
  lib/improver/tests/acceptance/test_wxcode.py
  lib/improver/tests/wxcode/wxcode/test_wxcode_utilities.py
  lib/improver/wxcode/wxcode_utilities.py
Labels: clize

#1077 wind-downscaling CLI to clize
  lib/improver/cli/wind_downscaling.py
  lib/improver/tests/acceptance/test_wind_downscaling.py
Labels: clize

#1035 IMPRO-1519: extrapolate clize
  lib/improver/cli/nowcast_extrapolate.py
  lib/improver/nowcasting/forecasting.py
  lib/improver/tests/acceptance/test_nowcast_extrapolate.py
  lib/improver/tests/acceptance/test_resolve_wind_components.py
  lib/improver/tests/nowcasting/forecasting/test_CreateExtrapolationForecast.py
Labels: clize

#1075 update-grid-metadata CLI to clize
  lib/improver/cli/update_grid_metadata.py
  lib/improver/metadata/amend.py
  lib/improver/tests/acceptance/test_update_grid_metadata.py
Labels: clize

#1078 temporal-interpolate CLI to clize
  lib/improver/cli/temporal_interpolate.py
  lib/improver/tests/acceptance/test_temporal_interpolate.py
Labels: clize

#1081 temp-lapse-rate CLI to clize
  lib/improver/cli/temp_lapse_rate.py
  lib/improver/tests/acceptance/test_temp_lapse_rate.py
Labels: clize
