Repository metoppv/improver, pull requests merged in 2021-09, with the labels that each got.

#1551 Updating timezone cli call
  improver/cli/map_to_timezones.py
Labels: BoM review required

#1556 Move statsmodels in environment yml files
  envs/environment_py37_iris30.yml
  envs/environment_py38_iris30.yml
  setup.cfg
Labels: FY21/22 Temperature calibration

#1559 Adds land-mask option to threshold CLI
  improver/cli/threshold.py
  improver/utilities/spatial.py
  improver_tests/acceptance/SHA256SUMS
  improver_tests/acceptance/test_threshold.py
  improver_tests/utilities/test_OccurrenceWithinVicinity.py
Labels: FY21/22 New Outputs

#1550 Adds LatitudeThreshold plugin and lightning-filter CLI
  improver/cli/lightning_from_cape_and_precip.py
  improver/lightning.py
  improver/synthetic_data/set_up_test_cubes.py
  improver/threshold.py
  improver/utilities/rescale.py
  improver_tests/acceptance/SHA256SUMS
  improver_tests/acceptance/test_lightning_from_cape_and_precip.py
  improver_tests/lightning/__init__.py
  improver_tests/lightning/test_LightningFromCapePrecip.py
  improver_tests/threshold/test_LatitudeDependentThreshold.py
  improver_tests/utilities/test_rescale.py
Labels: FY21/22 New Outputs

#1561 Re-label a diagnostic as a period diagnostic
  improver/cli/relabel_to_period.py
  improver/utilities/temporal.py
  improver_tests/acceptance/SHA256SUMS
  improver_tests/acceptance/test_relabel_to_period.py
  improver_tests/utilities/temporal/test_temporal.py
Labels: FY21/22 New Outputs

#1568 Modifies LightningFromCapePrecip plugin to accept 3h precipitation-rate-max data
  improver/lightning.py
  improver_tests/lightning/test_LightningFromCapePrecip.py
Labels: FY21/22 New Outputs
