Repository metoppv/improver, pull requests merged in 2021-02, with the labels that each got.

#1412 Replace assert with exception
  CONTRIBUTING.md
  improver/utilities/neighbourhood_tools.py
  improver_tests/utilities/test_neighbourhood_tools.py
Labels: good first review

#1413 Unit tests for neighbourhood_tools
  improver/utilities/neighbourhood_tools.py
  improver_tests/utilities/test_neighbourhood_tools.py
Labels: good first review

#1410 Minor edit to checking of overlapping forecast reference time bounds
  improver/calibration/reliability_calibration.py
  improver_tests/calibration/reliability_calibration/test_AggregateReliabilityCalibrationTables.py
Labels: good first review

#1411 IMPRO-1995: Bug fixes and timezone updates
  .github/workflows/tests.yml
  envs/environment_py36_iris22.yml
  envs/environment_py37_iris24.yml
  improver/generate_ancillaries/generate_timezone_mask.py
  improver_tests/acceptance/SHA256SUMS
  improver_tests/acceptance/test_generate_timezone_mask_ancillary.py
  improver_tests/generate_ancillaries/test_GenerateTimezoneMask.py
Labels: good first review

#1424 Update IMPROVER environment and tests
  .github/workflows/tests.yml
  envs/environment_py36_iris22.yml
  improver_tests/acceptance/SHA256SUMS
  improver_tests/acceptance/test_spot_extract.py
Labels: BoM review required

#1425 Reduced conda environment installation time on GH actions
  .github/workflows/tests.yml
Labels: MO review required

#1421 Update weather symbols code to avoid eval (fixes #1386)
  improver/wxcode/weather_symbols.py
  improver_tests/wxcode/wxcode/test_WeatherSymbols.py
Labels: MO review required

#1428 Allow bandit to return failure
  .github/workflows/tests.yml
Labels: MO review required
