Repository metoppv/improver, pull requests merged in 2024-07, with the labels that each got.

#2011 BLD: Fix CI Tests / Sphinx-Pytest-Coverage (conda-forge) failing
  envs/conda-forge.yml
Labels: Type:Bug, blue_team

#2003 Migrate CLI functionality to plugin layer subset 2
  improver/blending/weighted_blend.py
  improver/cli/extract.py
  improver/cli/freezing_rain.py
  improver/cli/hail_fraction.py
  improver/cli/hail_size.py
  improver/cli/interpolate_using_difference.py
  improver/cli/lightning_from_cape_and_precip.py
  improver/cli/nbhood.py
  improver/cli/phase_change_level.py
  improver/cli/phase_probability.py
  improver/cli/snow_splitter.py
  improver/cli/vertical_updraught.py
  improver/cli/wet_bulb_freezing_level.py
  improver/cli/wet_bulb_temperature.py
  improver/lightning.py
  improver/nbhood/nbhood.py
  improver/precipitation_type/freezing_rain.py
  improver/precipitation_type/hail_fraction.py
  improver/precipitation_type/snow_splitter.py
  improver/psychrometric_calculations/hail_size.py
  improver/psychrometric_calculations/precip_phase_probability.py
  improver/psychrometric_calculations/psychrometric_calculations.py
  improver/psychrometric_calculations/wet_bulb_temperature.py
  improver/utilities/complex_conversion.py
  improver/utilities/cube_extraction.py
  improver/utilities/cube_manipulation.py
  improver/utilities/interpolation.py
  improver/utilities/temporal_interpolation.py
  improver/wind_calculations/vertical_updraught.py
  improver/wind_calculations/wind_direction.py
  improver_tests/lightning/test_LightningFromCapePrecip.py
  improver_tests/nbhood/nbhood/test_MetaNeighbourhood.py
  improver_tests/precipitation_type/freezing_rain/test_FreezingRain.py
  improver_tests/precipitation_type/hail_fraction/test_HailFraction.py
  improver_tests/precipitation_type/snow_splitter/test_snow_splitter.py
  improver_tests/psychrometric_calculations/hail_size/test_HailSize.py
  improver_tests/psychrometric_calculations/precip_phase_probability/test_PrecipPhaseProbability.py
  improver_tests/psychrometric_calculations/test_PhaseChangeLevel.py
  improver_tests/psychrometric_calculations/wet_bulb_temperature/test_MetaWetBulbFreezingLevel.py
  improver_tests/psychrometric_calculations/wet_bulb_temperature/test_WetBulbTemperature.py
  improver_tests/utilities/complex_conversion/__init__.py
  improver_tests/utilities/complex_conversion/test_complex_to_deg.py
  improver_tests/utilities/complex_conversion/test_deg_to_complex.py
  improver_tests/utilities/complex_conversion/test_integration.py
  improver_tests/utilities/cube_extraction/test_ExtractSubCube.py
  improver_tests/utilities/test_InterpolateUsingDifference.py
  improver_tests/wind_calculations/vertical_updraught/test_VerticalUpdraught.py
  improver_tests/wind_calculations/wind_direction/test_WindDirection.py
Labels: Type:Maintenance, blue_team, MO review required

#2014 Apply mask to cube
  improver/cli/apply_mask.py
  improver/utilities/mask.py
  improver_tests/acceptance/SHA256SUMS
  improver_tests/acceptance/test_apply_mask.py
  improver_tests/utilities/test_mask.py
Labels: EPP

#2009 Plugin discovery
  improver/api/__init__.py
Labels: blue_team

#2021 BUG: Fix Scheduled Tests Sphinx-Pytest-Coverage
  envs/latest.yml
Labels: Type:Bug, test
