Repository metoppv/improver, pull requests merged in 2024-11, with the labels that each got.

#2035 Update decision tree to include an option for handling masked points
  doc/source/extended_documentation/categorical/build_a_decision_tree.rst
  improver/categorical/decision_tree.py
  improver/categorical/utilities.py
  improver_tests/categorical/decision_tree/__init__.py
  improver_tests/categorical/decision_tree/test_ApplyDecisionTree.py
  improver_tests/categorical/test_utilities.py
Labels: EPP

#2036 Fixes in support of configuration execution which call plugins directly (i.e. not via CLI)
  improver/cli/copy_attributes.py
  improver/utilities/copy_attributes.py
  improver/utilities/cube_extraction.py
  improver_tests/utilities/copy_attributes/test_CopyAttributes.py
  improver_tests/utilities/cube_extraction/test_ExtractLevel.py
Labels: Type:Bug, blue_team

#2048 Updated Readthedocs documentation in line with current practices.
  doc/source/Code-Style-Guide.rst
  doc/source/Dependencies.rst
  doc/source/Guidance-for-Reviewing-Code.rst
  doc/source/How-to-implement-a-command-line-utility.rst
  doc/source/Running-at-your-site.rst
  doc/source/about.rst
Labels: Type:Documentation

#2044 Adds cli and test to extract a cube from a cubelist
  improver/cli/cubelist_extract.py
  improver/utilities/cube_extraction.py
  improver_tests/acceptance/SHA256SUMS
  improver_tests/acceptance/test_cubelist_extract.py
  improver_tests/utilities/cube_extraction/test_cube_extraction.py
Labels: EPP

#2045 Update name of cubes from gradient module
  improver/utilities/spatial.py
  improver_tests/acceptance/SHA256SUMS
  improver_tests/utilities/spatial/test_GradientBetweenAdjacentGridSquares.py
Labels: EPP
